remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag # For better SEO

title: Suyash Agarwal #
description: Machine Learning and Neuroscience #

# Navigation items (will be used in _includes/header.html)
# Ensure the URLs match the filenames (e.g., /projects for projects.md)
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: Publications
    url: /publications
  - title: CV
    url: /cv
  - title: Blog
    url: /blog

# Social links (optional, can be used in footer or elsewhere)
linkedin_username: suyash--agarwal # From your original README.md

# Optional: Setup for Excerpts on the Blog page (if you use them)
# excerpt_separator: ```

### 2. `index.md` (Home/About Page)

```markdown
---
layout: default
title: Home
---

<img src="{{ '/assets/images/profile.png' | relative_url }}" alt="Suyash Agarwal" style="float: right; width: 150px; margin-left: 20px; border-radius: 50%;">

I am currently a Research Software Engineer at Cortexlab, UCL Queen Square Institute of Neurology.

I work on machine learning and AI methods for neural data analysis with Prof. Kenneth Harris.

Before moving to London, I was at Oxford University for 4 years studying for my MEng degree, and I have worked at the Computer Vision Lab at ETH Zurich.

Broadly, I am interested in machine learning and computational neuroscience but I have also studied computer vision, robotics, control theory, optimisation and bioinformatics. I am always interested in exploring these fields further.

You can find my LinkedIn [here](https://www.linkedin.com/in/suyash--agarwal/).