remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag # For better SEO

title: Suyash Agarwal #
description: Neural methods for neural data #

# Navigation items (will be used in _includes/header.html)
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: CV
    url: /cv
  - title: Publications
    url: /publications
  - title: Blog
    url: /blog

# Social links (optional, can be used in footer or elsewhere)
linkedin_username: suyash--agarwal # From your original README.md

# Optional: Setup for Excerpts on the Blog page (if you use them)
# excerpt_separator: ```
